### ISSUE TITLE
Invalid path alias:

### ISSUE THREAD

**Issue by Yurich84** [bluezed/yii2-scroll-top#1]
hi.
In Yii2 advansed I found an ecxeption: "Invalid path alias @bluezed/scrollTop/assets"

In file ScrollTopAsset.php
I changed
`public $sourcePath = '@bluezed/scrollTop/assets';`
to
`public $sourcePath = '@vendor/bluezed/yii2-scroll-top/assets';`
and it works.

**Comment by bluezed** [comment]
Sorry, but I cannot reproduce the issue.

I've just done a fresh installation of yii2-app-advanced via composer, initialised it and added `"bluezed/yii2-scroll-top": "*"` to the `composer.json` file and did a `composer update`.

Then I added this line `<?= \bluezed\scrollTop\ScrollTop::widget() ?>` to the `main.php` layout in `yii-application/frontend/views/layouts/`.

I can only assume that your configuration is somehow different from the default?

**Comment by Yurich84** [comment]
I cannot find the real reason of the exception, becouse on the localhost (Windows 7) everything is works great. But on the remote server I've got the issue.

**Comment by bluezed** [comment]
Can you have a look in this file: `yii-application/vendor/composer/autoload_psr4.php` which should have been auto-generated by composer.
There should be this line: `'bluezed\\scrollTop\\' => array($vendorDir . '/bluezed/yii2-scroll-top')`

If that's not the case then you might have an issue with composer on that machine...

**Comment by Yurich84** [comment]
I check my `yii-application/vendor/composer/autoload_psr4.php` file, and it has the line you said.
It must be something wrong with my site or configs.

**Comment by Yurich84** [comment]
I've got outside of your problem.
It concerns the register.
The problem was on server that is sensitive to register (Unix) but on the mac and windows it's ok.

**Comment by Yurich84** [comment]
i can fix it.
